import icon_open_properties_tab from './assets/icons/icon-open-properties-tab.svg';
import icon_open_plugins_tab from './assets/icons/icon-open-plugins-tab.svg';
import icon_open_editor_tab from './assets/icons/icon-open-editor-tab.svg';
import icon_collapse_folder from './assets/icons/icon-collapse-folder.svg';
import icon_expand_folder from './assets/icons/icon-expand-folder.svg';
import icon_flow_comment from './assets/icons/flow-icons/comment.png';
import icon_flow_foreach from './assets/icons/flow-icons/foreach.png';
import icon_output_param from './assets/icons/icon-output-param.png';
import icon_flow_action from './assets/icons/flow-icons/action.png';
import icon_flow_assign from './assets/icons/flow-icons/assign.png';
import icon_flow_switch from './assets/icons/flow-icons/switch.png';
import icon_input_param from './assets/icons/icon-input-param.png';
import icon_local_param from './assets/icons/icon-local-param.png';
import icon_open_github from './assets/icons/icon-open-github.png';
import icon_trash_light from './assets/icons/icon-trash-light.png';
import icon_flow_start from './assets/icons/flow-icons/start.png';
import icon_maximizar from './assets/icons/icon-maximizar.svg';
import icon_menu_user from './assets/icons/icon-menu-user.svg';
import icon_flow_end from './assets/icons/flow-icons/end.png';
import icon_download from './assets/icons/icon-download.png';
import icon_complete from './assets/icons/icon-complete.png';
import icon_minimize from './assets/icons/icon-minimize.png';
import icon_flow_if from './assets/icons/flow-icons/if.png';
import icon_restart from './assets/icons/icon-restart.svg';
import icon_plugins from './assets/icons/icon-plugins.png';
import icon_warning from './assets/icons/icon-warning.png';
import icon_folder from './assets/icons/icon-folder.png';
import icon_router from './assets/icons/icon-router.png';
import icon_action from './assets/icons/icon-action.png';
import icon_accont from './assets/icons/icon-accont.png';
import icon_config from './assets/icons/icon-config.png';
import icon_import from './assets/icons/icon-import.png';
import icon_error from './assets/icons/icon-error.png';
import icon_build from './assets/icons/icon-build.svg';
import icon_close from './assets/icons/icon-close.svg';
import icon_help from './assets/icons/icon-help.png';
import icon_info from './assets/icons/icon-info.png';
import icon_star from './assets/icons/icon-star.png';
import icon_tips from './assets/icons/icon-tips.png';
import icon_menu from './assets/icons/icon-menu.svg';
import icon_play from './assets/icons/icon-play.svg';
import icon_stop from './assets/icons/icon-stop.svg';

export const IconPropertiesTab = icon_open_properties_tab;
export const IconCollapsedFolder = icon_collapse_folder;
export const IconExpandedFolder = icon_expand_folder;
export const IconPluginsTab = icon_open_plugins_tab;
export const IconEditorTab = icon_open_editor_tab;
export const IconFlowComment = icon_flow_comment;
export const IconFlowForeach = icon_flow_foreach;
export const IconOutpuParam = icon_output_param;
export const IconFlowAction = icon_flow_action;
export const IconFlowAssign = icon_flow_assign;
export const IconFlowSwitch = icon_flow_switch;
export const IconInputParam = icon_input_param;
export const IconLocalParam = icon_local_param;
export const IconOpenGithub = icon_open_github;
export const IconFlowStart = icon_flow_start;
export const IconMaximize = icon_maximizar;
export const IconMenuUser = icon_menu_user;
export const IconDownload = icon_download;
export const IconComplete = icon_complete;
export const IconMinimize = icon_minimize;
export const IconTrash = icon_trash_light;
export const IconFlowEnd = icon_flow_end;
export const IconRestart = icon_restart;
export const IconPlugins = icon_plugins;
export const IconWarning = icon_warning;
export const IconFlowIf = icon_flow_if;
export const IconFolder = icon_folder;
export const IconRouter = icon_router;
export const IconAction = icon_action;
export const IconConfig = icon_config;
export const IconAccont = icon_accont;
export const IconImport = icon_import;
export const IconError = icon_error;
export const IconBuild = icon_build;
export const IconClose = icon_close;
export const IconMenu = icon_menu;
export const IconPlay = icon_play;
export const IconStop = icon_stop;
export const IconHelp = icon_help;
export const IconInfo = icon_info;
export const IconStar = icon_star;
export const IconTips = icon_tips;
